<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\dicontainer\\containertest' => '/ContainerTest.php',
                'spriebsch\\dicontainer\\dependencythathasuntypedconstructorparameter' => '/stubs/DependencyThatHasUntypedConstructorParameter.php',
                'spriebsch\\dicontainer\\testclassvirtualtypewithparameter' => '/stubs/TestClassVirtualTypeWithParameter.php',
                'spriebsch\\dicontainer\\testclasswithconfigurationdependency' => '/stubs/TestClassWitthConfigurationDependency.php',
                'spriebsch\\dicontainer\\testclasswithcontainerdependency' => '/stubs/TestClassWitthContainerDependency.php',
                'spriebsch\\dicontainer\\testclasswithdependency' => '/stubs/TestClassWithDependency.php',
                'spriebsch\\dicontainer\\testclasswithdependencythathasuntypedconstructorparameter' => '/stubs/TestClassWithDependencyThatHasUntypedConstructorParameter.php',
                'spriebsch\\dicontainer\\testclasswithlongnamefactorymethods' => '/stubs/TestClassWithLongNameFactoryMethods.php',
                'spriebsch\\dicontainer\\testclasswithmultipledependecies' => '/stubs/TestClassWithMultipleDependecies.php',
                'spriebsch\\dicontainer\\testclasswithoutconstructor' => '/stubs/TestClassWithoutConstructor.php',
                'spriebsch\\dicontainer\\testclasswithoutconstructorparameters' => '/stubs/TestClassWithoutConstructorParameters.php',
                'spriebsch\\dicontainer\\testclasswithscalarconstructorparameters' => '/stubs/TestClassWithScalarConstructorParameters.php',
                'spriebsch\\dicontainer\\testclasswithscalarconstructorparametersandshortmethod' => '/stubs/TestClassWithScalarConstructorParametersAndShortMethod.php',
                'spriebsch\\dicontainer\\testclasswithshortnamefactorymethod' => '/stubs/TestClassWithShortNameFactoryMethod.php',
                'spriebsch\\dicontainer\\testconfiguration' => '/stubs/TestConfiguration.php',
                'spriebsch\\dicontainer\\testdependency' => '/stubs/TestDependency.php',
                'spriebsch\\dicontainer\\testdependencyofdependency' => '/stubs/TestDependencyOfDependency.php',
                'spriebsch\\dicontainer\\testfactory' => '/stubs/TestFactory.php',
                'spriebsch\\dicontainer\\testfactorythatdoesnotextendabstractfactory' => '/stubs/TestFactoryThatDoesNotExtendAbstractFactory.php',
                'spriebsch\\testclasswithlongnamefactorymethods' => '/stubs/_TestClassWithLongNameFactoryMethods.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
