<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\dicontainer\\abstractfactory' => '/AbstractFactory.php',
                'spriebsch\\dicontainer\\autowireexception' => '/AutoWireException.php',
                'spriebsch\\dicontainer\\configuration' => '/Configuration.php',
                'spriebsch\\dicontainer\\container' => '/Container.php',
                'spriebsch\\dicontainer\\containerexception' => '/ContainerException.php',
                'spriebsch\\dicontainer\\type' => '/Type.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
